alias: "Congelador: Aviso Puerta Abierta"
description: "Avisa si la puerta del congelador queda abierta más de 1:30 min"
triggers:
  - trigger: state
    entity_id: binary_sensor.puerta_congelador_contact
    to: "on"
    for: "00:01:30"
actions:
  - action: media_player.play_media
    target:
      entity_id:
        - media_player.dormitorio
        - media_player.salon
    data:
      media_content_id: /local/notificaciones/nuevas/congelador_abierto.mp3
      media_content_type: audio/mp3
  - action: notify.alexa_media_echo_dot_estudio
    data:
      message: "¡Atención!. La puerta del congelador está abierta."
