alias: Congelador abierto
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
conditions:
  - condition: state
    entity_id: binary_sensor.puerta_congelador_contact
    state: "on"
    for:
      hours: 0
      minutes: 1
      seconds: 30
actions:
  - action: media_player.play_media
    data:
      media:
        media_content_id: /local/notificaciones/nuevas/congelador_abierto.mp3
        media_content_type: audio/mp3
        metadata: {}
    target:
      entity_id:
        - media_player.dormitorio
        - media_player.salon
  - action: notify.alexa_media_echo_dot_estudio
    data:
      message: "¡Atención!. La puerta del congelador está abierta. "
mode: single
